# Generated by Django 5.2 on 2025-04-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forme_juridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_forme', models.CharField(max_length=10)),
                ('libelle_forme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(max_length=10)),
                ('libelle_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_piece', models.CharField(max_length=50)),
                ('piece_identite', models.FileField(upload_to='identite/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('forme_juridique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.forme_juridique')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('description_projet', models.TextField()),
                ('plan_affaire', models.FileField(upload_to='plans_affaire/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.promoteur')),
                ('type_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.type_projet')),
            ],
        ),
    ]
