# Generated by Django 5.2 on 2025-04-08 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormeJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_forme', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('libelle_forme', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Forme juridique',
                'verbose_name_plural': 'Formes juridiques',
                'ordering': ['libelle_forme'],
            },
        ),
        migrations.CreateModel(
            name='TypeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('libelle_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de projet',
                'verbose_name_plural': 'Types de projet',
                'ordering': ['libelle_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='promoteur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Promoteur', 'verbose_name_plural': 'Promoteurs'},
        ),
        migrations.AddField(
            model_name='projet',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('SOUMIS', 'Soumis'), ('ETUDE', 'En étude'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='SOUMIS', max_length=10),
        ),
        migrations.AddField(
            model_name='promoteur',
            name='type_piece',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('PERMIS', 'Permis de conduire')], default='CNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='projet',
            name='plan_affaire',
            field=models.FileField(upload_to='plans_affaire/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='piece_identite',
            field=models.FileField(upload_to='identites/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='forme_juridique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.formejuridique'),
        ),
        migrations.AddConstraint(
            model_name='promoteur',
            constraint=models.UniqueConstraint(fields=('type_piece', 'numero_piece'), name='unique_piece_identite'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.typeprojet'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['nom_projet'], name='projets_pro_nom_pro_aa0b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['statut'], name='projets_pro_statut_2c59ef_idx'),
        ),
        migrations.DeleteModel(
            name='Forme_juridique',
        ),
        migrations.DeleteModel(
            name='Type_projet',
        ),
    ]
